baseURL = "http://mspencer.io/"
languageCode = "en-us"
title = "Michael Spencer"
theme = "sidebar"
preserveTaxonomyNames = true

[params]
subtitle = "Software Craftsman"
email = "sonrisesoftware@gmail.com"
github = "ibelieve"
